services:
  backend:
    image: dockermeet872/backend
    ports:
      - "8000:8000"
    environment:
      database_url: ${MONGO_URL}

  
  frontend:
    image: dockermeet872/frontend
    ports:
      - "5000:80"
    environment:
      REACT_APP_backendurl : http://backend:8000
